[정렬, 맵, 셋] 8월23일
Altu-Bitu-5/Altu-Bitu-KimYeonsu pull request #3
Opened 2023-08-23 09:54 UTC by sooooscode

### 인적사항
학번: 2176077
이름: 김연수
</br>

###과제제출
기존제출:

2023-08-25 14:18 UTC, kwakrhkr59 requested changes
**[정렬, 맵, 셋 구현 코드 리뷰 완료]**
19636(P1) 안녕하세요 연수님~ 제출해주신 필수 구현 문제 코드리뷰 완료되셨습니다! 이번 문제가 고려해야 하는 변수들이 많아서 까다로운 문제였는데 아주 깔끔하게 잘 해결해주셨네요👍👍 다만 딱 한 부분에서 문제가 있어 현재 백준에서 틀렸습니다가 뜨고 있는 것 같습니다😥 코드를 제출해주셔도 백준 통과가 되지 않으면 과제 제출 인정이 되지 않으니 반드시 확인 부탁드리겠습니다!!! 수정해주시고 리뷰어로 다시 호출해주시면 제가 확인 후 제출 처리해드리도록 하겠습니다😊

2023-08-25 14:18 UTC, kwakrhkr59 commented on 19636.cpp
> +}
요요 여부를 판단하는 부분을 함수화하여 출력부분을 간단하게 만들어주셨군요! 아주 좋습니다😍😍

2023-08-25 14:18 UTC, kwakrhkr59 commented on 19636.cpp
> +        }
체중과 기초대사량 변화 부분을 아주 깔끔하게 계산해주셨네요!👍👍

2023-08-25 14:18 UTC, kwakrhkr59 commented on 19636.cpp
> +    int W0, I0, T, D, I, A;
저희 알튜비튜에서는 변수명은 스네이크 표기법으로, 함수명은 카멜표기법으로 사용하고 있습니다! 변수명을 카멜표기법으로 쓰는 게 잘못된 것도 아니고 속하신 그룹에 따라 사용하는 코드 컨벤션이 달라질 수도 있어요😊 추후 다른 문제를 푸시게 되셨을 때 변수명, 함수명, 상수명에 사용되는 표기법이 혼용되지 않도록만 한 번 체크해주셔도 좋을 것 같네요😁

2023-08-25 14:18 UTC, kwakrhkr59 commented on 19636.cpp
> +            O = O + (I - O - A)/2;
P1 지금 다 너무너무 잘 풀어주셨는데 딱 이 부분 때문에 백준 통과가 되고 있지 않은 것 같네요😂 문제 아래쪽에 보시면 *음수의 나눗셈*에 대해 주의하라고 되어있었죠! c++에서의 음수의 나눗셈 방식이 이 문제에서의 나눗셈 기준과 맞지 않아서 그냥 2로 나눠줄 경우 백준 통과가 되지 않아요😥 해결 방법은 float을 사용하는 방법이 있을 것 같네요!(다른 방법도 있긴 있습니다) 해결이 어려우시다면 저희가 제공해드리는 샘플 코드를 한 번 확인해보셔도 좋을 것 같습니다😁

2023-08-25 22:02 UTC, sawoll approved these changes
P3: 안녕하세요 연수님! 필수문제 1431번, 14425번 코드 리뷰 완료했습니다.😀 두 문제 모두 아주 잘 풀어 주셨는데요! 각각 코드 구조와 컨테이너 사용 관련하여 코멘트 남겨드렸으니 확인해보시면 좋을 것 같습니다. 수고하셨습니다:)👍👍

2023-08-25 22:02 UTC, sawoll commented on 14425.cpp
> +    }
정렬과 이진 탐색을 사용하여 문제를 잘 풀어 주셨습니다.👍그런데, 직접 정렬해 주지 않아도 값을 삽입해 주면 정렬된 상태로 저장되는 컨테이너가 있었죠! 그걸 활용해 보면 어떨까요?😉

2023-08-29 12:05 UTC, sooooscode commented on 19636.cpp
> +            O = O + (I - O - A)/2;
해당 오류 부분 샘플 코드 참고하여 수정하였습니다.
검토 부탁 드립니다.

2023-09-06 08:32 UTC, kwakrhkr59 approved these changes
안녕하세요 연수님! 19636번 코드 고쳐주신 것 확인되셨습니다😊 수고 많으셨습니다 이제 머지하셔도 괜찮습니다:)

2023-09-07 03:11 UTC, merged